import os
from dotenv import load_dotenv
from langchain_text_splitters import RecursiveCharacterTextSplitter
from langchain_community.document_loaders import PyPDFLoader
from langchain_huggingface import HuggingFaceEndpointEmbeddings
from langchain_community.vectorstores import SKLearnVectorStore

load_dotenv()

# Resolve data directory relative to project root (two levels up from this file)
DATA_DIR = os.path.join(os.path.dirname(__file__), "..", "..", "data")

# RecursiveCharacterTextSplitter for PDFs (no markdown headers)
CHUNK_SIZE = 1000
CHUNK_OVERLAP = 200


def get_retrieval_files():
    """Dynamically fetch all PDF files from the data directory."""
    if not os.path.exists(DATA_DIR):
        return []
    
    pdf_files = [f for f in os.listdir(DATA_DIR) if f.lower().endswith('.pdf')]
    return sorted(pdf_files)  # Return sorted for consistent order


def load_and_split():
    splitter = RecursiveCharacterTextSplitter(
        chunk_size=CHUNK_SIZE,
        chunk_overlap=CHUNK_OVERLAP,
    )
    all_chunks = []
    retrieval_files = get_retrieval_files()
    
    if not retrieval_files:
        print("Warning: No PDF files found in data directory")
        return all_chunks
    
    for filename in retrieval_files:
        path = os.path.join(DATA_DIR, filename)
        if not os.path.exists(path):
            print(f"Warning: {filename} not found at {path}")
            continue
        try:
            loader = PyPDFLoader(path)
            documents = loader.load()
            chunks = splitter.split_documents(documents)
            for chunk in chunks:
                chunk.metadata["source"] = filename
            all_chunks.extend(chunks)
            print(f"Loaded {len(chunks)} chunks from {filename}")
        except Exception as e:
            print(f"Error loading {filename}: {e}")
    return all_chunks


def get_embeddings():
    # Keep model weights off the deployment image; embeddings are generated by
    # Hugging Face Inference API at runtime.
    token = os.getenv("HF_TOKEN") or os.getenv("HF_API_TOKEN")
    if not token:
        raise RuntimeError("HF_TOKEN is required for hosted embeddings")

    return HuggingFaceEndpointEmbeddings(
        model="sentence-transformers/all-MiniLM-L6-v2",
        huggingfacehub_api_token=token,
    )


def build_index():
    """Build the vectorstore in memory from documents."""
    chunks = load_and_split()
    print(f"Split into {len(chunks)} chunks")
    for c in chunks:
        print(f"  [{c.metadata.get('source')}] {c.metadata.get('h2', c.metadata.get('h1', ''))}")

    embeddings = get_embeddings()
    vectorstore = SKLearnVectorStore.from_documents(
        documents=chunks,
        embedding=embeddings,
    )
    print(f"Built vectorstore with {len(chunks)} chunks")
    return vectorstore


if __name__ == "__main__":
    build_index()